### ISSUE TITLE
How is this lib different than specifying <param name="encoding" value="binary"/> when configuring mod_erlang_event?

### ISSUE THREAD

**Issue by toraritte** [jamhed/fswitch#2]
Looking at `mod_erlang_event`'s source (and even at `mod_kazoo`'s), they are using [the function `ei_x_encode_binary`](http://erlang.org/doc/man/ei.html#ei_x_encode_binary) to achieve this.

Don't have any production experience using either of them, so just wondering if there's something I'm missing. Thanks!

**Comment by jamhed** [comment]
@toraritte, not sure what you're talking about. The intent of this library is to provide an abstraction layer, sort of to introduce a notion of call and call events on erlang side.
